{'project_id': '3130', 'year': '1984', 'x': -489960, 'y': 2289780, 'plot_id': '8436', 'strata': '41'}
Pandas(Index=0, project_id='3130', plot_id='8436', x=-489960, y=2289780)
called process_plot
Pandas(Index=0, project_id='3130', plot_id='8436', x=-489960, y=2289780)
8436
Directory '/efs/timesync/1984/audit/' already exists.
Data has been pickled and saved to '/efs/timesync/1984/audit/1984_8436_3130.p'.
Failed qa: 1984-04-10T17:09:39.074012Z
.......Failed qa: 1984-05-05T17:03:23.4270130Z
Failed qa: 1984-05-12T17:10:00.474066Z
..............Failed qa: 1984-05-28T17:10:27.156041Z
.......Failed qa: 1984-06-13T17:10:57.6910130Z
..............Failed qa: 1984-06-29T17:10:58.594534Z
..............Failed qa: 1984-07-15T17:11:11.989072Z
..............Failed qa: 1984-08-25T17:06:19.405069Z
Failed qa: 1984-09-01T17:12:32.640076Z
.......Failed qa: 1984-09-10T17:06:23.929044Z
Failed qa: 1984-09-26T17:06:25.229562Z
..............Failed qa: 1984-11-04T17:12:26.020063Z
..............Failed qa: 1984-11-20T17:12:21.555519Z
.......Data has been pickled and saved to '/efs/timesync/1984/audit/1984_8436_3130_qa_rejects.p'.
Success tracking goes here
