{'project_id': '3130', 'year': '1984', 'x': 575550, 'y': 769680, 'plot_id': '23451', 'strata': '41'}
Pandas(Index=0, project_id='3130', plot_id='23451', x=575550, y=769680)
called process_plot
Pandas(Index=0, project_id='3130', plot_id='23451', x=575550, y=769680)
23451
Directory '/efs/timesync/1984/audit/' already exists.
Data has been pickled and saved to '/efs/timesync/1984/audit/1984_23451_3130.p'.
Failed qa: 1984-03-25T15:54:12.632069Z
.......Failed qa: 1984-04-13T16:05:15.346047Z
.......Failed qa: 1984-04-29T16:05:24.5800130Z
..............Failed qa: 1984-06-16T16:06:12.4920940Z
..............Failed qa: 1984-09-04T16:07:57.3870940Z
..............Failed qa: 1984-10-06T16:08:11.312066Z
..............Failed qa: 1984-11-07T16:08:00.443066Z
Failed qa: 1984-11-23T16:07:58.182572Z
Data has been pickled and saved to '/efs/timesync/1984/audit/1984_23451_3130_qa_rejects.p'.
Success tracking goes here
