{'project_id': '3130', 'year': '1984', 'x': 2021760, 'y': 2378310, 'plot_id': '5141', 'strata': '41'}
Pandas(Index=0, project_id='3130', plot_id='5141', x=2021760, y=2378310)
called process_plot
Pandas(Index=0, project_id='3130', plot_id='5141', x=2021760, y=2378310)
5141
Directory '/efs/timesync/1984/audit/' already exists.
Data has been pickled and saved to '/efs/timesync/1984/audit/1984_5141_3130.p'.
.......Failed qa: 1984-05-27T14:48:52.4640000Z
.......Failed qa: 1984-06-10T15:01:19.139066Z
Failed qa: 1984-06-12T14:49:11.4660190Z
.......Failed qa: 1984-06-28T14:49:24.6080880Z
Failed qa: 1984-07-05T14:56:03.6500310Z
Failed qa: 1984-07-28T15:02:16.521044Z
Failed qa: 1984-08-31T14:50:59.2140000Z
Failed qa: 1984-09-16T14:51:02.3740310Z
.......Failed qa: 1984-09-30T15:03:12.519072Z
.......Failed qa: 1984-10-16T15:03:09.953060Z
Failed qa: 1984-10-18T14:50:59.7150560Z
.......Failed qa: 1984-11-01T15:03:04.016047Z
Failed qa: 1984-11-03T14:50:53.3000440Z
.......Failed qa: 1984-11-17T15:02:57.432047Z
.......Data has been pickled and saved to '/efs/timesync/1984/audit/1984_5141_3130_qa_rejects.p'.
Success tracking goes here
