{'project_id': '1211', 'year': '1989', 'x': 849810, 'y': 1218750, 'plot_id': '287', 'strata': '41'}
Pandas(Index=0, project_id='1211', plot_id='287', x=849810, y=1218750)
called process_plot
Pandas(Index=0, project_id='1211', plot_id='287', x=849810, y=1218750)
287
Directory '/efs/timesync/1989/audit/' already exists.
Data has been pickled and saved to '/efs/timesync/1989/audit/1989_0287_1211.p'.
..............Failed qa: 1989-01-30T16:00:55.4780310Z
.....................Failed qa: 1989-03-19T15:59:57.6020310Z
..............Failed qa: 1989-04-20T15:59:48.0020500Z
..............Failed qa: 1989-05-08T15:47:14.0300130Z
.......Failed qa: 1989-05-22T15:59:18.4800060Z
..............Failed qa: 1989-06-09T15:46:38.6550690Z
Failed qa: 1989-06-23T15:58:39.8150380Z
.............................................................................Failed qa: 1989-10-06T15:50:30.170056Z
............................Data has been pickled and saved to '/efs/timesync/1989/audit/1989_0287_1211_qa_rejects.p'.
Success tracking goes here
