{'project_id': '1211', 'year': '1989', 'x': -1398480, 'y': 2421300, 'plot_id': '2317', 'strata': '41'}
Pandas(Index=0, project_id='1211', plot_id='2317', x=-1398480, y=2421300)
called process_plot
Pandas(Index=0, project_id='1211', plot_id='2317', x=-1398480, y=2421300)
2317
Directory '/efs/timesync/1989/audit/' already exists.
Data has been pickled and saved to '/efs/timesync/1989/audit/1989_2317_1211.p'.
.......Failed qa: 1989-03-24T17:54:28.1880310Z
.......Failed qa: 1989-04-09T17:54:53.670556Z
..............Failed qa: 1989-04-25T17:54:34.652044Z
.......Failed qa: 1989-05-11T17:54:20.746569Z
.......Failed qa: 1989-05-27T17:54:05.695034Z
..............Failed qa: 1989-06-12T17:53:43.865559Z
.....................Failed qa: 1989-06-28T17:53:27.999575Z
.....................Failed qa: 1989-07-14T17:53:08.122075Z
.....................Failed qa: 1989-07-30T17:52:49.244022Z
.....................Failed qa: 1989-08-15T17:52:25.624047Z
.....................Failed qa: 1989-08-31T17:52:06.202566Z
..............Failed qa: 1989-09-16T17:51:33.205510Z
............................Failed qa: 1989-10-18T17:50:42.876519Z
.......Data has been pickled and saved to '/efs/timesync/1989/audit/1989_2317_1211_qa_rejects.p'.
Success tracking goes here
