{'project_id': '1211', 'year': '1989', 'x': 708780, 'y': 1050690, 'plot_id': '3983', 'strata': '41'}
Pandas(Index=0, project_id='1211', plot_id='3983', x=708780, y=1050690)
called process_plot
Pandas(Index=0, project_id='1211', plot_id='3983', x=708780, y=1050690)
3983
Directory '/efs/timesync/1989/audit/' already exists.
Data has been pickled and saved to '/efs/timesync/1989/audit/1989_3983_1211.p'.
Failed qa: 1989-01-07T15:56:12.4200190Z
.......Failed qa: 1989-01-30T16:01:19.2990810Z
.......Failed qa: 1989-02-15T16:01:29.596565Z
..............Failed qa: 1989-03-19T16:00:33.339544Z
Failed qa: 1989-04-04T16:00:48.4300130Z
.......Failed qa: 1989-04-20T16:00:23.744041Z
.......Failed qa: 1989-05-06T16:00:13.732529Z
.......Failed qa: 1989-05-22T15:59:54.296559Z
.......Failed qa: 1989-06-07T15:59:39.496553Z
.......Failed qa: 1989-06-23T15:59:15.564553Z
.......Failed qa: 1989-07-09T15:58:59.896072Z
.......Failed qa: 1989-07-25T15:58:40.747022Z
.......Failed qa: 1989-08-26T15:57:58.711041Z
Failed qa: 1989-09-04T15:52:12.0390060Z
.......Failed qa: 1989-09-27T15:57:13.765547Z
..............Data has been pickled and saved to '/efs/timesync/1989/audit/1989_3983_1211_qa_rejects.p'.
Success tracking goes here
