{'project_id': '1211', 'year': '1989', 'x': 858630, 'y': 2054100, 'plot_id': '1395', 'strata': '41'}
Pandas(Index=0, project_id='1211', plot_id='1395', x=858630, y=2054100)
called process_plot
Pandas(Index=0, project_id='1211', plot_id='1395', x=858630, y=2054100)
1395
Directory '/efs/timesync/1989/audit/' already exists.
Data has been pickled and saved to '/efs/timesync/1989/audit/1989_1395_1211.p'.
............................Failed qa: 1989-03-03T15:59:02.0800060Z
Failed qa: 1989-03-19T15:58:10.173557Z
Failed qa: 1989-04-04T15:58:01.3570690Z
.......Failed qa: 1989-04-20T15:58:00.561069Z
.......Failed qa: 1989-05-06T15:57:50.398551Z
.......Failed qa: 1989-05-22T15:57:19.0420190Z
.......Failed qa: 1989-06-07T15:57:16.148531Z
.......Failed qa: 1989-06-23T15:56:52.350550Z
..............Failed qa: 1989-07-09T15:56:36.675003Z
.......Failed qa: 1989-07-25T15:56:17.658544Z
.......Failed qa: 1989-08-26T15:55:35.387028Z
..............Failed qa: 1989-09-27T15:54:50.492053Z
..............Data has been pickled and saved to '/efs/timesync/1989/audit/1989_1395_1211_qa_rejects.p'.
Success tracking goes here
