{'project_id': '1211', 'year': '1989', 'x': 232620, 'y': 1690320, 'plot_id': '3629', 'strata': '41'}
Pandas(Index=0, project_id='1211', plot_id='3629', x=232620, y=1690320)
called process_plot
Pandas(Index=0, project_id='1211', plot_id='3629', x=232620, y=1690320)
3629
Directory '/efs/timesync/1989/audit/' already exists.
Data has been pickled and saved to '/efs/timesync/1989/audit/1989_3629_1211.p'.
..............Failed qa: 1989-01-17T16:30:40.6880000Z
...................................Failed qa: 1989-03-06T16:30:14.8690190Z
.......Failed qa: 1989-03-22T16:29:34.2870310Z
..............Failed qa: 1989-04-09T16:17:24.2230940Z
.......Failed qa: 1989-04-23T16:29:29.0590310Z
..........................................Failed qa: 1989-06-26T16:28:21.6840560Z
............................Failed qa: 1989-07-28T16:27:44.2250380Z
..............Failed qa: 1989-08-13T16:27:21.4170810Z
............................Failed qa: 1989-09-30T16:26:19.0380810Z
............................Failed qa: 1989-11-01T16:25:20.0750690Z
..............Failed qa: 1989-11-17T16:24:43.1750940Z
.......Data has been pickled and saved to '/efs/timesync/1989/audit/1989_3629_1211_qa_rejects.p'.
Success tracking goes here
